---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-with-background-analysis-and-rollback-window
spec:
  replicas: 2
  rollbackWindow:
    revisions: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-background-analysis
  template:
    metadata:
      labels:
        app: rollout-background-analysis
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FOO
              value: BAZ
  strategy:
    canary:
      analysis:
        templates:
          - templateName: pass
      steps:
        - setWeight: 50
        - pause: { duration: 5s }
        - setWeight: 100
